### ISSUE TITLE
Bracken mpa output

### ISSUE THREAD

**Issue by fconstancias** [jenniferlu717/Bracken#18]
Hi all,
I am using kraken and bracken to estimate bacterial community composition of metagenomic samples.
Is there any way to get an mpa (i.e., "metaphlan") output out of bracken as it i possible with kraken with the kraken-mpa-report script ?
I really like the stratification with the full taxonomic path which is very comfortable to import then in R and phyloseq...

If you have any idea / suggestion.

Thanks a lot.

Flo

**Comment by jenniferlu717** [comment]
Added a script that can be used to convert the Bracken/Kraken reports to mpa. Please let me know if you find any issues with it.

**Comment by FCMicrobes** [comment]
Thanks for the script.
I am able to use it on kraken output but not on the bracken output which is split at a taxonomic level. I was wondering if it was possible to have an mpa format from Bracken.

**Comment by FCMicrobes** [comment]
It also seems that --intermediate-ranks flag is always set to True.

**Comment by jenniferlu717** [comment]
It should work on the bracken report output? Bracken outputs both kraken-style report files and the bracken output. 

I think I fixed the script for the intermediate-ranks flag.

**Comment by jenniferlu717** [comment]
Can you let me know any issues you have with the newest script?

**Comment by FCMicrobes** [comment]
Thanks a lot for the clarification, I missed the kraken-style report of Bracken.

I have run the mpa updated script to generate mpa report but I still have the intermediate ranks. 

e.g., r_root|x_cellular organisms|[...]|f_Burkholderiaceae|g_Burkholderia|x_Burkholderia cepacia complex|s_Burkho[...]

Do you have a bash solution to delete them?

**Comment by jenniferlu717** [comment]
Not off the top of my head. Let me double check the script options and I'll try to have a new version up in a day

**Comment by jenniferlu717** [comment]
What command line did you run? I just tested it myself and the intermediate ranks are not included (I also added the sample data report mpa and mpa_with_intermediate ranks) Try the newest script again?

**Comment by FCMicrobes** [comment]
Thanks the latest version is working. 
I still have the r_root| and may I suggest to use the exact same metaphlan format to be able to use metaphlan2krona.py script to generate krona plot easily (k__ | p__ ... instead of d_ | p_ ... Or maybe it is because metaphlan2krona.py requires percentage as an input) . I have tried and it doesn't work on the output. Thanks a ton

**Comment by jenniferlu717** [comment]
Can you link me to that script? I'll make another version where it will use d instead of k and remove the root.

**Comment by FCMicrobes** [comment]
Here it is :
https://bitbucket.org/nsegata/metaphlan/src/2f1b17a1f4e9775fe1ce42c8481279a5e69f291f/conversion_scripts/metaphlan2krona.py?at=default&fileviewer=file-view-default

**Comment by snehamurthy21** [comment]
> Added a script that can be used to convert the Bracken/Kraken reports to mpa. Please let me know if you find any issues with it.

Can you tell me where I can find this script?
Thank you
